# See https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
# for more info

# Please consult conda-forge/core before doing this
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.12                  # [osx and x86_64]
    
